    openapi: 3.0.0
    info:
      title: Sample API
      version: 0.1.1
    components:
      schemas:
        User:
          properties:
            id:
              type: integer
              minimum: 0
            name:
              type: string
          required:  
            - id
            - name
    paths:
      /users/:
        get:
          summary: Returns a user by ID.
          parameters:
            - name: userId
              in: query
              required: true
              description: The ID of the user to return.
              schema:
                type: integer
                minimum: 0
          responses:
              '200':
                description: Ok
          operationId: GetUser
      /groups:
        get:
          summary: Returns groups
          parameters:
            - name: groupName
              in: query
              required: true
              description: The ID of the user to return.
              schema:
                type: string
          responses:
              '200':
                description: Ok
          operationId: GetGroup
      